name: EC2 Deploy using OIDC

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 🔐 AWS Login using OIDC (NO secrets)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::815512685331:role/github-actions-ec2-role
          aws-region: ap-south-1

      # 🧱 Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 🚀 Init Terraform
      - name: Terraform Init
        run: terraform init

      # 🚀 Apply Infrastructure
      - name: Terraform Apply
        run: terraform apply -auto-approve